### ISSUE TITLE
add state management separate from frontend db

### ISSUE THREAD

**Issue by tlmn** [dw-innovation/dw-kid2-graph-frontend-prototype#18]
@nikonikoniko As briefly discussed we should have some state management for handling state that cannot or should not be dealt with in the frontend db (eg state of the app before initialization of db). I would suggest we go for https://github.com/pmndrs/zustand

**Comment by nikonikoniko** [comment]
I like how that library looks.  

Considerations for non-db state:

1) What in particular will it store?
  - the config object
  - ... any more?
2) Persistence
  - can this state easily be saved and loaded from local storage?
  - to a file?

my worry with zustand is that the 'actions' also live in the state object, and js functions can't be cleanly serialized.

**Comment by tlmn** [comment]
> I like how that library looks, and I think you're right about the need.
> 
> Considerations for non-db state:
> 
>     1. What in particular will it store?
>        
>        * the config object?
>        * ... any more?
> 
>     2. Persistence
>        
>        * can this state easily be saved and loaded from local storage?
>        * to a file?
> 
> 
> my worry with zustand is that the 'actions' also live in the state object, and js functions can't be cleanly serialized, nor do we want it in this case, mixing app logic in with data.
> 
> we could use something like this and then on persisting the state do something like `save(without(functions, state))`

Actually, you can save the state to localStorage and also load the initial state from there: https://github.com/pmndrs/zustand/issues/195

**Comment by nikonikoniko** [comment]
> > Here is a library that is similar, but separates the `actions` from the `state` - also for consideration.
> 
> Think there is a link missing in your post?

added, sorry.  The link is: https://github.com/derrickbeining/react-atom

**Comment by nikonikoniko** [comment]
> > ```
> > 2. Persistence
> >    
> >    * can this state easily be saved and loaded from local storage?
> >    * to a file?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > my worry with zustand is that the 'actions' also live in the state object, and js functions can't be cleanly serialized, nor do we want it in this case, mixing app logic in with data.
> > we could use something like this and then on persisting the state do something like `save(without(functions, state))`
> 
> Actually, you can save the state to localStorage and also load the initial state from there: [pmndrs/zustand#195](https://github.com/pmndrs/zustand/issues/195)

Aha, so in this case, your store would always save the `data` in it's own key, and the actions separately?

so instead of 

```javascript
{ 
  fishes: {}
  birds: {}
  addFish: () => {}
  addBird: () => {}
}
```

You would have something like

```javascript
{
  data: {
    fishes: {}
    birds: {}
  }
  addFish: () => {}
  addBird: () => {}
}
```

?

This could work for me but I wonder if there is any efficiency lost in nesting the data like that.  That might be worth asking.

**Comment by tlmn** [comment]
I think the state managed through Zustand would be kind of limited: configuration and app state mostly. So, I guess we wouldn't run into performance issues on that end (if there were any with nested data).

**Comment by nikonikoniko** [comment]
Very good point.
